version: '2'
services:
  mysql:
    env_file: db.env
    image: mysql:5.6
    ports:
        - "3306"
  web:
    build: .
    volumes:
      - ~/sites/docker-drupal8:/app/docroot
    ports:
      - "8000:80"
      - "443"
      - "22"
    links:
      - mysql
    depends_on:
      - mysql
